services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=10
      - N8N_RUNNERS_ENABLED=true

      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./project_files:/files

volumes:
  n8n_data:
  project_files:

